runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: gunicorn
  version: 19.7.1
- name: requests
  version: 2.21.0
- name: future
  version: 0.16.0
